# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("finalized", "Finalized"),
                            ("booked", "Booked"),
                            ("emailed", "Emailed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("overdue", "Overdue"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pdf_file_path", models.CharField(blank=True, max_length=500)),
                ("is_pdf_generated", models.BooleanField(default=False)),
                ("is_emailed", models.BooleanField(default=False)),
                (
                    "external_accounting_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_invoice",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("unit", models.CharField(default="each", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("service_period_start", models.DateTimeField(blank=True, null=True)),
                ("service_period_end", models.DateTimeField(blank=True, null=True)),
                ("is_taxable", models.BooleanField(default=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("section_header", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "finance_invoiceline",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
