# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("invoices", "0001_initial"),
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_lines",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bill",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="billing.bill",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["tenant", "invoice", "service_type"],
                name="finance_inv_tenant__5242e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["sort_order"], name="finance_inv_sort_or_c6ebd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "customer", "status"],
                name="finance_inv_tenant__b4518c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="finance_inv_due_dat_b93853_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="finance_inv_invoice_89da8a_idx"
            ),
        ),
    ]
