# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("tariff_profile", "0001_initial"),
        ("pricing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="touprofileassignment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tou_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="touprofileassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tou_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="touprofileassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="touprofileassignment",
            name="tou_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tariff_profile.electricitytouprofile",
            ),
        ),
        migrations.AddField(
            model_name="touperioddefinition",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="touperioddefinition",
            name="tou_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_definitions",
                to="tariff_profile.electricitytouprofile",
            ),
        ),
        migrations.AddField(
            model_name="touholidaycalendar",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tou_holidays",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="touholidaycalendar",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="electricitytouprofile",
            name="base_profile",
            field=models.OneToOneField(
                help_text="Links to the generic TOU profile in finance.pricing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity_specifics",
                to="pricing.tariffprofile",
            ),
        ),
        migrations.AddField(
            model_name="electricitytouprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_electricity_tou_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="electricitytouprofile",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity_tou_profiles",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="touprofileassignment",
            index=models.Index(
                fields=["tou_profile", "status"], name="tariff_prof_tou_pro_903a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touprofileassignment",
            index=models.Index(
                fields=["assigned_from", "assigned_to"],
                name="tariff_prof_assigne_6ee031_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touprofileassignment",
            index=models.Index(
                fields=["status", "priority"], name="tariff_prof_status_d603d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="touprofileassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("assigned_to__isnull", True),
                    ("assigned_to__gt", models.F("assigned_from")),
                    _connector="OR",
                ),
                name="tou_assignment_valid_date_range",
            ),
        ),
        migrations.AddIndex(
            model_name="touperioddefinition",
            index=models.Index(
                fields=["tou_profile", "period_code"],
                name="tariff_prof_tou_pro_e3eb7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touperioddefinition",
            index=models.Index(
                fields=["period_type", "applicable_season"],
                name="tariff_prof_period__9ffa4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touperioddefinition",
            index=models.Index(
                fields=["start_time", "end_time"], name="tariff_prof_start_t_f6d59e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touperioddefinition",
            index=models.Index(
                fields=["priority"], name="tariff_prof_priorit_6a5835_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="touperioddefinition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("spans_midnight", True),
                    ("end_time__gt", models.F("start_time")),
                    _connector="OR",
                ),
                name="tou_period_valid_time_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="touperioddefinition",
            unique_together={("tou_profile", "period_code", "applicable_season")},
        ),
        migrations.AddIndex(
            model_name="touholidaycalendar",
            index=models.Index(
                fields=["tenant", "holiday_date"], name="tariff_prof_tenant__d7efcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touholidaycalendar",
            index=models.Index(
                fields=["holiday_type", "region_code"],
                name="tariff_prof_holiday_ea19f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touholidaycalendar",
            index=models.Index(
                fields=["is_active", "applies_nationwide"],
                name="tariff_prof_is_acti_9eaabc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touholidaycalendar",
            index=models.Index(
                fields=["holiday_date", "tou_treatment"],
                name="tariff_prof_holiday_83fc5e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="touholidaycalendar",
            unique_together={("tenant", "holiday_name", "holiday_date")},
        ),
        migrations.AddIndex(
            model_name="electricitytouprofile",
            index=models.Index(
                fields=["tenant", "profile_type"], name="tariff_prof_tenant__ea93ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytouprofile",
            index=models.Index(
                fields=["profile_code"], name="tariff_prof_profile_98003e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytouprofile",
            index=models.Index(
                fields=["distributor_code", "network_profile_code"],
                name="tariff_prof_distrib_223b86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytouprofile",
            index=models.Index(
                fields=["effective_date", "expiry_date"],
                name="tariff_prof_effecti_60f545_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytouprofile",
            index=models.Index(
                fields=["is_active"], name="tariff_prof_is_acti_715e7f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="electricitytouprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expiry_date__isnull", True),
                    ("expiry_date__gt", models.F("effective_date")),
                    _connector="OR",
                ),
                name="electricity_tou_profile_valid_date_range",
            ),
        ),
    ]
