# Generated by Django 4.2.5 on 2025-08-16 01:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BroadbandPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pricing_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("plan_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("fibre", "Fibre Broadband"),
                            ("wireless", "Fixed Wireless"),
                            ("rural", "Rural Broadband"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("12_month", "12 Month"),
                            ("24_month", "24 Month"),
                            ("open_term", "Open Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terms_url", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rate_details", models.TextField()),
                (
                    "monthly_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "data_allowance",
                    models.CharField(default="Unlimited", max_length=50),
                ),
                ("download_speed", models.CharField(blank=True, max_length=50)),
                ("upload_speed", models.CharField(blank=True, max_length=50)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Broadband Plan",
                "verbose_name_plural": "Broadband Plans",
                "ordering": ["plan_id"],
            },
        ),
        migrations.CreateModel(
            name="ElectricityPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pricing_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("plan_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price Plan"),
                            ("tou", "Time of Use Plan"),
                            ("spot", "Spot Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("12_month", "12 Month"),
                            ("24_month", "24 Month"),
                            ("open_term", "Open Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terms_url", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rate_details", models.TextField()),
                (
                    "monthly_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "standard_daily_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "standard_variable_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low_user_daily_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low_user_variable_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "peak_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "off_peak_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low_user_peak_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low_user_off_peak_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "wholesale_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "network_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Electricity Plan",
                "verbose_name_plural": "Electricity Plans",
                "ordering": ["plan_id"],
            },
        ),
        migrations.CreateModel(
            name="MobilePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pricing_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("plan_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("prepaid", "Prepaid"),
                            ("postpaid", "Postpaid"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("12_month", "12 Month"),
                            ("24_month", "24 Month"),
                            ("open_term", "Open Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terms_url", models.CharField(max_length=200)),
                ("city", models.CharField(default="nz", max_length=50)),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rate_details", models.TextField()),
                (
                    "monthly_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("data_allowance", models.CharField(max_length=50)),
                ("minutes", models.CharField(max_length=50)),
                ("texts", models.CharField(max_length=50)),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sim_card_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "data_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minute_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "text_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("international_minutes", models.CharField(default="0", max_length=50)),
                ("international_texts", models.CharField(default="0", max_length=50)),
                ("international_data", models.CharField(default="0", max_length=50)),
                ("hotspot_data", models.CharField(default="0", max_length=50)),
                ("rollover_data", models.BooleanField(default=False)),
                ("data_speed", models.CharField(default="Full Speed", max_length=50)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mobile Plan",
                "verbose_name_plural": "Mobile Plans",
                "ordering": ["plan_id"],
            },
        ),
        migrations.CreateModel(
            name="PricingRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "service_availability",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("both", "Both Services"),
                            ("all", "All Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Region",
                "verbose_name_plural": "Pricing Regions",
                "ordering": ["display_name"],
            },
        ),
    ]
