# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_pricing", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileplan",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobile_plans",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="electricityplan",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity_plans",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="broadbandplan",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadband_plans",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="mobileplan",
            index=models.Index(
                fields=["tenant", "is_active"], name="public_pric_tenant__cef1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mobileplan",
            index=models.Index(
                fields=["tenant", "plan_type", "is_active"],
                name="public_pric_tenant__9819d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mobileplan",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="public_pric_valid_f_f49fd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mobileplan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plan_id"), name="unique_mobile_plan_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="electricityplan",
            index=models.Index(
                fields=["tenant", "city", "is_active"],
                name="public_pric_tenant__8128b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricityplan",
            index=models.Index(
                fields=["tenant", "plan_type", "is_active"],
                name="public_pric_tenant__eba20e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricityplan",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="public_pric_valid_f_8f8004_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="electricityplan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plan_id"), name="unique_electricity_plan_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="broadbandplan",
            index=models.Index(
                fields=["tenant", "city", "is_active"],
                name="public_pric_tenant__9d62be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadbandplan",
            index=models.Index(
                fields=["tenant", "plan_type", "is_active"],
                name="public_pric_tenant__c35f6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadbandplan",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="public_pric_valid_f_fcbd08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="broadbandplan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plan_id"), name="unique_broadband_plan_per_tenant"
            ),
        ),
    ]
