version: '3.8'

services:
  spoton-portal-uat:
    image: ghcr.io/kairos-enterprises-nz/spoton-platform-portal:${IMAGE_TAG:-uat-latest}
    networks:
      - edge_net
    expose:
      - "80"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://uat.api.spoton.co.nz
      - VITE_WEB_URL=https://uat.spoton.co.nz
      - VITE_PORTAL_URL=https://uat.portal.spoton.co.nz
      - VITE_STAFF_URL=https://uat.staff.spoton.co.nz
      - VITE_KEYCLOAK_URL=https://auth.spoton.co.nz
      - VITE_KEYCLOAK_REALM=spoton-uat
      - VITE_KEYCLOAK_CLIENT_ID=customer-uat-portal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 30s
        order: stop-first
      placement: {}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  edge_net:
    external: true
    name: edge_net
