# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_id",
                    models.IntegerField(
                        help_text="Original address ID from source dataset"
                    ),
                ),
                (
                    "source_dataset",
                    models.CharField(
                        help_text="Source dataset identifier", max_length=255
                    ),
                ),
                ("change_id", models.IntegerField(help_text="Change tracking ID")),
                ("full_address_number", models.CharField(blank=True, max_length=255)),
                ("full_road_name", models.CharField(blank=True, max_length=255)),
                ("full_address", models.CharField(db_index=True, max_length=1024)),
                ("territorial_authority", models.CharField(blank=True, max_length=255)),
                ("unit_type", models.CharField(blank=True, max_length=100)),
                ("unit_value", models.CharField(blank=True, max_length=100)),
                ("level_type", models.CharField(blank=True, max_length=100)),
                ("level_value", models.CharField(blank=True, max_length=100)),
                ("address_number_prefix", models.CharField(blank=True, max_length=50)),
                ("address_number", models.CharField(blank=True, max_length=50)),
                ("address_number_suffix", models.CharField(blank=True, max_length=50)),
                ("address_number_high", models.CharField(blank=True, max_length=50)),
                ("road_name_prefix", models.CharField(blank=True, max_length=50)),
                ("road_name", models.CharField(blank=True, max_length=255)),
                ("road_type_name", models.CharField(blank=True, max_length=100)),
                ("road_suffix", models.CharField(blank=True, max_length=50)),
                ("water_name", models.CharField(blank=True, max_length=255)),
                ("water_body_name", models.CharField(blank=True, max_length=255)),
                (
                    "suburb_locality",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "town_city",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("address_class", models.CharField(blank=True, max_length=100)),
                ("address_lifecycle", models.CharField(blank=True, max_length=100)),
                ("gd2000_xcoord", models.FloatField(blank=True, null=True)),
                ("gd2000_ycoord", models.FloatField(blank=True, null=True)),
                ("shape_X", models.FloatField(blank=True, null=True)),
                ("shape_Y", models.FloatField(blank=True, null=True)),
                ("road_name_ascii", models.CharField(blank=True, max_length=255)),
                ("water_name_ascii", models.CharField(blank=True, max_length=255)),
                ("water_body_name_ascii", models.CharField(blank=True, max_length=255)),
                ("suburb_locality_ascii", models.CharField(blank=True, max_length=255)),
                ("town_city_ascii", models.CharField(blank=True, max_length=255)),
                ("full_road_name_ascii", models.CharField(blank=True, max_length=255)),
                ("full_address_ascii", models.CharField(blank=True, max_length=1024)),
            ],
            options={
                "db_table": "address_plans_address",
                "indexes": [
                    models.Index(
                        fields=["full_address"], name="address_pla_full_ad_d48eb8_idx"
                    ),
                    models.Index(
                        fields=["suburb_locality", "town_city"],
                        name="address_pla_suburb__347454_idx",
                    ),
                    models.Index(
                        fields=["address_id", "source_dataset"],
                        name="address_pla_address_1d0696_idx",
                    ),
                ],
            },
        ),
    ]
