# Generated by Django 4.2.5 on 2025-08-16 01:53

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricityTariff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tariff_code", models.CharField(max_length=50, unique=True)),
                ("distributor_code", models.CharField(blank=True, max_length=20)),
                ("network_tariff_code", models.CharField(blank=True, max_length=50)),
                (
                    "tariff_category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("low_user", "Low User"),
                            ("standard_user", "Standard User"),
                            ("general", "General"),
                            ("controlled", "Controlled Load"),
                            ("uncontrolled", "Uncontrolled Load"),
                            ("tou", "Time of Use"),
                            ("demand", "Demand"),
                            ("capacity", "Capacity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("single_phase", "Single Phase"),
                            ("three_phase", "Three Phase"),
                            ("lv", "Low Voltage"),
                            ("hv", "High Voltage"),
                        ],
                        default="single_phase",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_kva_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum capacity in kVA",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "capacity_kva_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum capacity in kVA",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "low_user_threshold_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Low user threshold in kWh per month",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "lines_charge_daily",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Daily lines charge",
                        max_digits=8,
                    ),
                ),
                (
                    "lines_charge_variable",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Variable lines charge per kWh",
                        max_digits=8,
                    ),
                ),
                (
                    "electricity_authority_levy",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="EA levy per kWh",
                        max_digits=8,
                    ),
                ),
                (
                    "reconciliation_participant",
                    models.CharField(blank=True, max_length=100),
                ),
                ("settlement_code", models.CharField(blank=True, max_length=20)),
                (
                    "required_meter_type",
                    models.CharField(
                        choices=[
                            ("accumulation", "Accumulation"),
                            ("interval", "Interval"),
                            ("smart", "Smart Meter"),
                            ("prepaid", "Prepaid"),
                        ],
                        default="accumulation",
                        max_length=20,
                    ),
                ),
                ("has_tou_pricing", models.BooleanField(default=False)),
                ("has_seasonal_pricing", models.BooleanField(default=False)),
                ("has_demand_charges", models.BooleanField(default=False)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("eligibility_criteria", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisterTariffMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "register_code",
                    models.CharField(
                        help_text="Register code (e.g., A+, A-, B1, B2, C1, C2)",
                        max_length=10,
                    ),
                ),
                (
                    "register_type",
                    models.CharField(
                        choices=[
                            ("import_active", "Import Active (A+)"),
                            ("export_active", "Export Active (A-)"),
                            ("import_reactive", "Import Reactive (B+)"),
                            ("export_reactive", "Export Reactive (B-)"),
                            ("controlled_load", "Controlled Load"),
                            ("uncontrolled_load", "Uncontrolled Load"),
                            ("generation", "Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tariff_component",
                    models.CharField(
                        choices=[
                            ("energy_charge", "Energy Charge"),
                            ("demand_charge", "Demand Charge"),
                            ("capacity_charge", "Capacity Charge"),
                            ("controlled_load", "Controlled Load"),
                            ("generation_credit", "Generation Credit"),
                            ("reactive_charge", "Reactive Charge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tou_period",
                    models.CharField(
                        blank=True,
                        help_text="TOU period (peak, shoulder, off_peak, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Multiplier for register readings",
                        max_digits=6,
                    ),
                ),
                (
                    "is_billing_register",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this register is used for billing",
                    ),
                ),
                (
                    "is_settlement_register",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this register is used for market settlement",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TariffApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applied_from", models.DateField()),
                ("applied_to", models.DateField(blank=True, null=True)),
                (
                    "application_reason",
                    models.CharField(
                        choices=[
                            ("new_connection", "New Connection"),
                            ("customer_request", "Customer Request"),
                            ("tariff_change", "Tariff Change"),
                            ("meter_upgrade", "Meter Upgrade"),
                            ("load_change", "Load Change"),
                            ("regulatory_requirement", "Regulatory Requirement"),
                            ("correction", "Correction"),
                        ],
                        max_length=25,
                    ),
                ),
                ("has_custom_pricing", models.BooleanField(default=False)),
                ("custom_pricing_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("application_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TariffVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.CharField(max_length=20)),
                (
                    "version_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("creation", "Initial Creation"),
                            ("price_update", "Price Update"),
                            ("structure_change", "Structure Change"),
                            ("regulatory_update", "Regulatory Update"),
                            ("correction", "Correction"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_description", models.TextField()),
                ("change_reason", models.TextField(blank=True)),
                (
                    "tariff_data",
                    models.JSONField(
                        help_text="Complete tariff configuration at this version"
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "regulatory_filing_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("ea_notification_sent", models.BooleanField(default=False)),
                ("ea_notification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_date"],
            },
        ),
    ]
