# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tariffs", "0001_initial"),
        ("pricing", "0002_initial"),
        ("users", "0001_initial"),
        ("connections", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariffversion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tariff_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tariffversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tariff_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tariffversion",
            name="electricity_tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="tariffs.electricitytariff",
            ),
        ),
        migrations.AddField(
            model_name="tariffversion",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariff_applications",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tariff_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariff_applications",
                to="connections.connection",
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tariff_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="electricity_tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="tariffs.electricitytariff",
            ),
        ),
        migrations.AddField(
            model_name="tariffapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="registertariffmapping",
            name="electricity_tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register_mappings",
                to="tariffs.electricitytariff",
            ),
        ),
        migrations.AddField(
            model_name="registertariffmapping",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="electricitytariff",
            name="base_tariff",
            field=models.OneToOneField(
                help_text="Links to the generic tariff in finance.pricing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity_specifics",
                to="pricing.tariff",
            ),
        ),
        migrations.AddField(
            model_name="electricitytariff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_electricity_tariffs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="electricitytariff",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity_tariffs",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffversion",
            index=models.Index(
                fields=["electricity_tariff", "version_date"],
                name="tariffs_tar_electri_0893f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffversion",
            index=models.Index(
                fields=["change_type", "requires_approval"],
                name="tariffs_tar_change__41b8c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffversion",
            index=models.Index(
                fields=["approved_at"], name="tariffs_tar_approve_758b95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tariffapplication",
            index=models.Index(
                fields=["account", "connection", "applied_from"],
                name="tariffs_tar_account_0cb8ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffapplication",
            index=models.Index(
                fields=["electricity_tariff", "status"],
                name="tariffs_tar_electri_e1b091_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffapplication",
            index=models.Index(
                fields=["applied_from", "applied_to"],
                name="tariffs_tar_applied_57f3a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffapplication",
            index=models.Index(
                fields=["status", "approved_at"], name="tariffs_tar_status_1b1aa6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tariffapplication",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("applied_to__isnull", True),
                    ("applied_to__gt", models.F("applied_from")),
                    _connector="OR",
                ),
                name="tariff_application_valid_date_range",
            ),
        ),
        migrations.AddIndex(
            model_name="registertariffmapping",
            index=models.Index(
                fields=["electricity_tariff", "register_code"],
                name="tariffs_reg_electri_d10ddb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registertariffmapping",
            index=models.Index(
                fields=["register_type", "tariff_component"],
                name="tariffs_reg_registe_61264e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registertariffmapping",
            index=models.Index(
                fields=["tou_period"], name="tariffs_reg_tou_per_0dcc0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registertariffmapping",
            unique_together={("electricity_tariff", "register_code", "tou_period")},
        ),
        migrations.AddIndex(
            model_name="electricitytariff",
            index=models.Index(
                fields=["tenant", "tariff_category"],
                name="tariffs_ele_tenant__4db717_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytariff",
            index=models.Index(
                fields=["tariff_code"], name="tariffs_ele_tariff__359f17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytariff",
            index=models.Index(
                fields=["distributor_code", "network_tariff_code"],
                name="tariffs_ele_distrib_6e6ded_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytariff",
            index=models.Index(
                fields=["effective_date", "expiry_date"],
                name="tariffs_ele_effecti_e2dff7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electricitytariff",
            index=models.Index(
                fields=["is_published"], name="tariffs_ele_is_publ_a06ab6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="electricitytariff",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expiry_date__isnull", True),
                    ("expiry_date__gt", models.F("effective_date")),
                    _connector="OR",
                ),
                name="electricity_tariff_valid_date_range",
            ),
        ),
    ]
