# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("export_core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationsubmission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsubmission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsubmission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketsubmission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketsubmission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="marketsubmission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsubmission",
            index=models.Index(
                fields=["tenant", "trading_date", "trading_period"],
                name="energy_reco_tenant__58100e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsubmission",
            index=models.Index(
                fields=["participant_code", "submission_type"],
                name="energy_reco_partici_a9619e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsubmission",
            index=models.Index(
                fields=["status", "submission_deadline"],
                name="energy_reco_status_7d272e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsubmission",
            index=models.Index(
                fields=["submitted_at"], name="energy_reco_submitt_3f38f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsubmission",
            constraint=models.UniqueConstraint(
                fields=("tenant", "trading_date", "trading_period", "submission_type"),
                name="unique_reconciliation_submission",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubmission",
            index=models.Index(
                fields=["tenant", "submission_type"],
                name="energy_mark_tenant__645c9f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubmission",
            index=models.Index(
                fields=["status", "due_date"], name="energy_mark_status_0da324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubmission",
            index=models.Index(
                fields=["reporting_period_start", "reporting_period_end"],
                name="energy_mark_reporti_3c1b38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubmission",
            index=models.Index(
                fields=["participant_code"], name="energy_mark_partici_cb3e7e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketsubmission",
            constraint=models.UniqueConstraint(
                fields=("tenant", "submission_id"), name="unique_market_submission_id"
            ),
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["tenant", "export_type"], name="energy_expo_tenant__5d63ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["status", "started_at"], name="energy_expo_status_198116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["data_start_date", "data_end_date"],
                name="energy_expo_data_st_4e326c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["recipient", "transmission_method"],
                name="energy_expo_recipie_add1a9_idx",
            ),
        ),
    ]
