# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistryMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., 'RS-010', 'RS-020'",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "INBOUND"), ("OUTBOUND", "OUTBOUND")],
                        max_length=10,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="The parsed content of the file."),
                ),
                (
                    "sftp_filename",
                    models.CharField(
                        help_text="The original filename on the SFTP server.",
                        max_length=255,
                    ),
                ),
                (
                    "is_manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="True if this message was generated by a user action.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "energy_registrymessage",
            },
        ),
        migrations.CreateModel(
            name="SwitchRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gaining_trader_code",
                    models.CharField(
                        default="SPON",
                        help_text="Market participant code (typically SPON for SpotOn)",
                        max_length=20,
                    ),
                ),
                (
                    "losing_trader_code",
                    models.CharField(
                        default="UNKNOWN",
                        help_text="Previous retailer's market participant code",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("NT_SENT", "NT Sent"),
                            ("AN_RECEIVED", "AN Received"),
                            ("CS_AWAITED", "CS Awaited"),
                            ("COMPLETED", "Completed"),
                            ("RR_SENT", "RR Sent"),
                            ("RR_RECEIVED", "RR Received"),
                            ("READING_CORRECTED", "Reading Corrected"),
                            ("WITHDRAWAL_SENT", "Withdrawal Sent"),
                            ("WITHDRAWAL_RECEIVED", "Withdrawal Received"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="INITIATED",
                        max_length=30,
                    ),
                ),
                (
                    "nt_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of successful NT file upload.",
                        null=True,
                    ),
                ),
                ("actual_transfer_date", models.DateField(blank=True, null=True)),
                (
                    "override_active",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all automated DAGs will skip execution for this request.",
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True,
                        help_text="Mandatory reason if an override is active.",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switch_request",
                        to="contracts.electricitycontract",
                    ),
                ),
            ],
            options={
                "db_table": "energy_switchrequest",
            },
        ),
    ]
