# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("switching", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="switchrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="switchrequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="switchrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrymessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrymessage",
            name="switch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="switching.switchrequest",
            ),
        ),
        migrations.AddField(
            model_name="registrymessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="registrymessage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="switchrequest",
            index=models.Index(
                fields=["tenant", "status"], name="energy_swit_tenant__7f1a4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="switchrequest",
            index=models.Index(
                fields=["gaining_trader_code", "losing_trader_code"],
                name="energy_swit_gaining_486b77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="switchrequest",
            index=models.Index(
                fields=["actual_transfer_date"], name="energy_swit_actual__50f364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrymessage",
            index=models.Index(
                fields=["tenant", "message_type", "direction"],
                name="energy_regi_tenant__0d25a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrymessage",
            index=models.Index(
                fields=["switch_request", "timestamp"],
                name="energy_regi_switch__fd1877_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrymessage",
            index=models.Index(
                fields=["sftp_filename"], name="energy_regi_sftp_fi_dcf01e_idx"
            ),
        ),
    ]
