# Generated by Django 4.2.5 on 2025-08-16 01:53

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BroadbandContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                (
                    "technology_type",
                    models.CharField(
                        choices=[
                            ("fibre", "Fibre"),
                            ("vdsl", "VDSL"),
                            ("adsl", "ADSL"),
                            ("cable", "Cable"),
                            ("wireless", "Wireless"),
                            ("satellite", "Satellite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ont_serial", models.CharField(blank=True, max_length=50)),
                ("router_serial", models.CharField(blank=True, max_length=50)),
                (
                    "equipment_provided",
                    models.JSONField(
                        default=list, help_text="List of equipment provided by ISP"
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "download_speed_mbps",
                    models.PositiveIntegerField(help_text="Download speed in Mbps"),
                ),
                (
                    "upload_speed_mbps",
                    models.PositiveIntegerField(help_text="Upload speed in Mbps"),
                ),
                (
                    "data_allowance_gb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Monthly data allowance in GB (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "uptime_guarantee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("99.50"),
                        help_text="Uptime guarantee percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Support"),
                            ("standard", "Standard Support"),
                            ("premium", "Premium Support"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "installation_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("installation_notes", models.TextField(blank=True)),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("term_months", models.PositiveIntegerField()),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly service fee", max_digits=8
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_installation", "Pending Installation"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("signed_by_customer", models.BooleanField(default=False)),
                ("cooling_off_expires", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=200)),
                (
                    "early_termination_fee_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amendment_number", models.CharField(max_length=50)),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("rate_change", "Rate Change"),
                            ("term_extension", "Term Extension"),
                            ("service_addition", "Service Addition"),
                            ("service_removal", "Service Removal"),
                            ("address_change", "Address Change"),
                            ("billing_change", "Billing Change"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("reason", models.TextField()),
                ("changes_summary", models.JSONField(blank=True, default=dict)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("requested_date", models.DateTimeField()),
                ("effective_date", models.DateTimeField()),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("implemented_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractConnectionAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_id",
                    models.UUIDField(
                        help_text="ID of the connection (energy.connections.Connection)"
                    ),
                ),
                ("assigned_date", models.DateField(default=django.utils.timezone.now)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Contract Connection Assignment",
                "verbose_name_plural": "Contract Connection Assignments",
                "db_table": "contracts_contractconnectionassignment",
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Main Contract"),
                            ("amendment", "Amendment"),
                            ("terms", "Terms & Conditions"),
                            ("schedule", "Rate Schedule"),
                            ("application", "Application Form"),
                            ("authorization", "Authorization"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("document_name", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_current", models.BooleanField(default=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractPlanAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity Plan"),
                            ("broadband", "Broadband Plan"),
                            ("mobile", "Mobile Plan"),
                            ("gas", "Gas Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(
                        help_text="ID of the plan in the registry (ElectricityPlan.plan_id, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        help_text="Cached plan name for quick access", max_length=200
                    ),
                ),
                ("assigned_date", models.DateField(default=django.utils.timezone.now)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Contract Plan Assignment",
                "verbose_name_plural": "Contract Plan Assignments",
                "db_table": "contracts_contractplanassignment",
            },
        ),
        migrations.CreateModel(
            name="ContractService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_type", models.CharField(max_length=20)),
                ("service_plan", models.CharField(max_length=100)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("service_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("activation_date", models.DateTimeField(blank=True, null=True)),
                ("deactivation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contracts_contractservice",
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_code", models.CharField(max_length=50, unique=True)),
                ("template_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("multi_service", "Multi-Service Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "customer_segment",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("small_business", "Small Business"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("government", "Government"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "terms_template",
                    models.TextField(
                        help_text="Contract terms template with placeholders"
                    ),
                ),
                (
                    "default_term_months",
                    models.PositiveIntegerField(
                        default=12, help_text="Default contract term in months"
                    ),
                ),
                (
                    "minimum_term_months",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum allowable contract term"
                    ),
                ),
                (
                    "maximum_term_months",
                    models.PositiveIntegerField(
                        default=36, help_text="Maximum allowable contract term"
                    ),
                ),
                ("has_early_termination_fee", models.BooleanField(default=False)),
                (
                    "early_termination_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Early termination fee amount",
                        max_digits=8,
                    ),
                ),
                (
                    "cooling_off_days",
                    models.PositiveIntegerField(
                        default=10, help_text="Cooling-off period in days"
                    ),
                ),
                (
                    "required_clauses",
                    models.JSONField(
                        default=list, help_text="List of required legal clauses"
                    ),
                ),
                (
                    "compliance_requirements",
                    models.JSONField(
                        default=dict, help_text="Regulatory compliance requirements"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity Contract"),
                            ("broadband", "Broadband Contract"),
                            ("mobile", "Mobile Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_id", models.UUIDField()),
                ("version_number", models.CharField(max_length=20)),
                (
                    "version_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("creation", "Initial Creation"),
                            ("amendment", "Amendment"),
                            ("renewal", "Renewal"),
                            ("termination", "Termination"),
                            ("suspension", "Suspension"),
                            ("reactivation", "Reactivation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_description", models.TextField()),
                ("change_reason", models.TextField(blank=True)),
                (
                    "contract_data",
                    models.JSONField(
                        help_text="Complete contract data at this version"
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("legal_review_required", models.BooleanField(default=False)),
                ("legal_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_date"],
            },
        ),
        migrations.CreateModel(
            name="ElectricityContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("icp_code", models.CharField(max_length=15)),
                ("gxp_code", models.CharField(blank=True, max_length=10)),
                ("network_company", models.CharField(blank=True, max_length=100)),
                (
                    "load_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("low_user", "Low User"),
                            ("standard_user", "Standard User"),
                            ("controlled_load", "Controlled Load"),
                            ("uncontrolled_load", "Uncontrolled Load"),
                            ("time_of_use", "Time of Use"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "agreed_capacity_kva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Agreed maximum demand in kVA",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "maximum_demand_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum demand in kW",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("meter_number", models.CharField(blank=True, max_length=50)),
                (
                    "meter_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accumulation", "Accumulation"),
                            ("interval", "Interval"),
                            ("smart", "Smart Meter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("network_tariff_code", models.CharField(blank=True, max_length=50)),
                (
                    "distribution_charge",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Distribution charge per kWh",
                        max_digits=8,
                    ),
                ),
                (
                    "transmission_charge",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Transmission charge per kWh",
                        max_digits=8,
                    ),
                ),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("term_months", models.PositiveIntegerField()),
                (
                    "custom_unit_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Custom unit rate override",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "custom_daily_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Custom daily charge override",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("READY", "Ready for Switching"),
                            ("SWITCH_GAIN", "Switch Gain in Progress"),
                            ("ACTIVE", "Active"),
                            ("SWITCH_LOSS", "Switch Loss in Progress"),
                            ("SWITCH_WITHDRAWAL_PENDING", "Switch Withdrawal Pending"),
                            ("INACTIVE", "Inactive"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when status first transitioned to READY. Marks the start of the NT submission SLA.",
                        null=True,
                    ),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("signed_by_customer", models.BooleanField(default=False)),
                ("signed_by_retailer", models.BooleanField(default=False)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=200)),
                (
                    "early_termination_fee_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contracts_electricitycontract",
            },
        ),
        migrations.CreateModel(
            name="MobileContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("mobile_number", models.CharField(max_length=20)),
                ("sim_id", models.CharField(blank=True, max_length=50)),
                (
                    "iccid",
                    models.CharField(
                        blank=True, help_text="SIM card ICCID", max_length=22
                    ),
                ),
                ("device_imei", models.CharField(blank=True, max_length=17)),
                ("device_make", models.CharField(blank=True, max_length=50)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("device_provided", models.BooleanField(default=False)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("prepaid", "Prepaid"),
                            ("postpaid", "Postpaid"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "voice_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Monthly voice minutes (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "sms_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Monthly SMS count (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "data_allowance_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly data allowance in GB (null for unlimited)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("2g", "2G"),
                            ("3g", "3G"),
                            ("4g", "4G LTE"),
                            ("5g", "5G"),
                        ],
                        default="4g",
                        max_length=10,
                    ),
                ),
                ("international_roaming", models.BooleanField(default=False)),
                ("international_calling", models.BooleanField(default=False)),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("term_months", models.PositiveIntegerField()),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly service fee", max_digits=8
                    ),
                ),
                (
                    "activation_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "device_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "device_monthly_payment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("device_payment_months", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_activation", "Pending Activation"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("porting_required", models.BooleanField(default=False)),
                ("previous_provider", models.CharField(blank=True, max_length=100)),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("signed_by_customer", models.BooleanField(default=False)),
                ("cooling_off_expires", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=200)),
                (
                    "early_termination_fee_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity Supply"),
                            ("gas", "Gas Supply"),
                            ("broadband", "Broadband Service"),
                            ("mobile", "Mobile Service"),
                            ("bundle", "Multi-Service Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("bi_monthly", "Bi-Monthly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_day",
                    models.IntegerField(
                        default=1, help_text="Day of month/quarter for billing"
                    ),
                ),
                (
                    "base_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "contracts_servicecontract",
            },
        ),
    ]
