#!/bin/bash
# Setup All SFTP Environment Variables
# Run this script to configure all SFTP connections for Airflow DAGs

echo "🔧 Setting up All SFTP Environment Variables"
echo "=============================================="

# Common SFTP Server Configuration (All using the same working server)
SFTP_HOST="192.168.1.6"
SFTP_PORT="2222"
SFTP_USER="ams"
SFTP_PASS="ams"
SFTP_PRIVATE_KEY_PATH="/app/keys/ams_key"
SFTP_PRIVATE_KEY_PASSPHRASE="ams"

echo "📡 Configuring WITS/NZX Environment Variables..."
# WITS/NZX SFTP Configuration
export NZX_HOST="$SFTP_HOST"
export NZX_PORT="$SFTP_PORT"
export NZX_USER="$SFTP_USER"
export NZX_PASS="$SFTP_PASS"
export NZX_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export NZX_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export NZX_REMOTE_PATH="/data/to_yesp/WITS"
export NZX_FILE_PATTERN="^final(\d{14})\.csv$"
export NZX_TIMEOUT="30"
export NZX_RETRY_COUNT="3"
export NZX_VERIFY_SSL="false"

echo "🏢 Configuring BCMM (BlueCurrent Mass Market) Environment Variables..."
# BCMM SFTP Configuration
export BCMM_HOST="$SFTP_HOST"
export BCMM_PORT="$SFTP_PORT"
export BCMM_USER="$SFTP_USER"
export BCMM_PASS="$SFTP_PASS"
export BCMM_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export BCMM_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export BCMM_REMOTE_PATH="/data/to_yesp/DRR"
export BCMM_FILE_PATTERN="^RMNGCS[A-Z]{4}\d{14}IC\.C\d{2}\.csv$"
export BCMM_TIMEOUT="30"
export BCMM_RETRY_COUNT="3"

echo "🏭 Configuring BCCI (BlueCurrent Commercial & Industrial) Environment Variables..."
# BCCI SFTP Configuration
export BCCI_HOST="$SFTP_HOST"
export BCCI_PORT="$SFTP_PORT"
export BCCI_USER="$SFTP_USER"
export BCCI_PASS="$SFTP_PASS"
export BCCI_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export BCCI_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export BCCI_REMOTE_PATH="/data/to_yesp/HERM"
export BCCI_FILE_PATTERN="^ci_readings_\d{8}\.csv$"
export BCCI_TIMEOUT="30"
export BCCI_RETRY_COUNT="3"

echo "🧠 Configuring IHUB (IntelliHub) Environment Variables..."
# IHUB SFTP Configuration
export IHUB_HOST="$SFTP_HOST"
export IHUB_PORT="$SFTP_PORT"
export IHUB_USER="$SFTP_USER"
export IHUB_PASS="$SFTP_PASS"
export IHUB_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export IHUB_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export IHUB_REMOTE_PATH="/data/to_yesp/IHUB"
export IHUB_FILE_PATTERN="^intellihub_\d{8}\.csv$"
export IHUB_TIMEOUT="30"
export IHUB_RETRY_COUNT="3"

echo "📊 Configuring MTRX (Matrix) Environment Variables..."
# MTRX SFTP Configuration
export MTRX_HOST="$SFTP_HOST"
export MTRX_PORT="$SFTP_PORT"
export MTRX_USER="$SFTP_USER"
export MTRX_PASS="$SFTP_PASS"
export MTRX_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export MTRX_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export MTRX_REMOTE_PATH="/data/to_yesp/MTRX"
export MTRX_FILE_PATTERN="^influx_data_\d{8}\.csv$"
export MTRX_TIMEOUT="30"
export MTRX_RETRY_COUNT="3"

echo "🔌 Configuring SMCO (SmartCo) Environment Variables..."
# SMCO SFTP Configuration
export SMCO_HOST="$SFTP_HOST"
export SMCO_PORT="$SFTP_PORT"
export SMCO_USER="$SFTP_USER"
export SMCO_PASS="$SFTP_PASS"
export SMCO_PRIVATE_KEY_PATH="$SFTP_PRIVATE_KEY_PATH"
export SMCO_PRIVATE_KEY_PASSPHRASE="$SFTP_PRIVATE_KEY_PASSPHRASE"
export SMCO_REMOTE_PATH="/data/to_yesp/SMCO"
export SMCO_FILE_PATTERN="^smartco_\d{8}\.csv$"
export SMCO_TIMEOUT="30"
export SMCO_RETRY_COUNT="3"

echo ""
echo "✅ All environment variables configured:"
echo ""
echo "📡 WITS/NZX:"
echo "   NZX_HOST: $NZX_HOST"
echo "   NZX_PORT: $NZX_PORT"
echo "   NZX_USER: $NZX_USER"
echo "   NZX_REMOTE_PATH: $NZX_REMOTE_PATH"
echo ""
echo "🏢 BCMM (BlueCurrent Mass Market):"
echo "   BCMM_HOST: $BCMM_HOST"
echo "   BCMM_REMOTE_PATH: $BCMM_REMOTE_PATH"
echo ""
echo "🏭 BCCI (BlueCurrent Commercial):"
echo "   BCCI_HOST: $BCCI_HOST"
echo "   BCCI_REMOTE_PATH: $BCCI_REMOTE_PATH"
echo ""
echo "🧠 IHUB (IntelliHub):"
echo "   IHUB_HOST: $IHUB_HOST"
echo "   IHUB_REMOTE_PATH: $IHUB_REMOTE_PATH"
echo ""
echo "📊 MTRX (Matrix):"
echo "   MTRX_HOST: $MTRX_HOST"
echo "   MTRX_REMOTE_PATH: $MTRX_REMOTE_PATH"
echo ""
echo "🔌 SMCO (SmartCo):"
echo "   SMCO_HOST: $SMCO_HOST"
echo "   SMCO_REMOTE_PATH: $SMCO_REMOTE_PATH"

echo ""
echo "🎯 Configuration Summary:"
echo "   - All DAGs now use environment variables (no hardcoded credentials)"
echo "   - All point to working SFTP server ($SFTP_HOST:$SFTP_PORT)"
echo "   - Remote paths organized by data type (DRR, HERM, WITS, etc.)"
echo "   - Consistent authentication using same credentials"

echo ""
echo "🚀 Next Steps:"
echo "1. Source this script: source setup_all_env.sh"
echo "2. Test connections: python3 debug_wits_fetch.py"
echo "3. Validate DAGs: python3 test_dag_imports.py"
echo "4. Deploy to production with proper secrets management"

echo ""
echo "💡 For production deployment:"
echo "   - Use Kubernetes secrets or similar for credentials"
echo "   - Store environment variables in secure configuration management"
echo "   - Never commit credentials to version control"
echo "   - Consider using service accounts instead of user credentials"

echo ""
echo "📁 SFTP Folder Structure:"
echo "   /data/to_yesp/"
echo "   ├── DRR/     # BCMM Daily Register Reads"
echo "   ├── HERM/    # BCCI Historical Energy Records"
echo "   ├── WITS/    # NZX Wholesale Prices"
echo "   ├── IHUB/    # IntelliHub Data"
echo "   ├── MTRX/    # Matrix Data"
echo "   └── SMCO/    # SmartCo Data" 