# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserOnboardingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Essential address info: full_address, service availability",
                    ),
                ),
                (
                    "services_chosen",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected services: mobile, broadband, electricity",
                    ),
                ),
                (
                    "plan_selections",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected plans for each service",
                    ),
                ),
                (
                    "personal_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DOB, ID details, contact preferences",
                    ),
                ),
                (
                    "service_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Service start dates, transfer types, device preferences",
                    ),
                ),
                (
                    "payment_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Payment method and billing preferences",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True, default=dict, help_text="Communication preferences"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "communication_preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
