# Generated by Django 4.2.5 on 2025-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="interested_in_mobile",
            field=models.BooleanField(
                default=False,
                help_text="User wants to be notified when mobile services become available",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="interested_in_power",
            field=models.BooleanField(
                default=False,
                help_text="User wants to be notified when power services become available",
            ),
        ),
    ]
