# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("issue_date", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "is_combined_bill",
                    models.BooleanField(default=False, help_text="Multi-utility bill"),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("pdf_file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_bill",
            },
        ),
        migrations.CreateModel(
            name="BillAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("correction", "Correction"),
                            ("refund", "Refund"),
                            ("write_off", "Write Off"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("billing_error", "Billing Error"),
                            ("meter_error", "Meter Error"),
                            ("customer_complaint", "Customer Complaint"),
                            ("system_error", "System Error"),
                            ("goodwill", "Goodwill"),
                            ("regulatory", "Regulatory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("authorization_date", models.DateTimeField()),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_code", models.CharField(max_length=50)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_billing_config",
            },
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("bundle", "Multi-Service Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("bi_monthly", "Bi-Monthly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                (
                    "cycle_day",
                    models.IntegerField(
                        default=1, help_text="Day of month for billing"
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("next_bill_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_billingcycle",
            },
        ),
        migrations.CreateModel(
            name="BillingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("bundle", "Multi-Service Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("run_date", models.DateTimeField()),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="tenant|service|contract|period_start|period_end",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_customers", models.IntegerField(default=0)),
                ("bills_generated", models.IntegerField(default=0)),
                ("bills_failed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_billed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("energy_charge", "Energy Charge"),
                            ("demand_charge", "Demand Charge"),
                            ("fixed_charge", "Fixed Charge"),
                            ("network_charge", "Network Charge"),
                            ("transmission_charge", "Transmission Charge"),
                            ("service_charge", "Service Charge"),
                            ("tax", "Tax"),
                            ("discount", "Discount"),
                            ("credit", "Credit"),
                            ("adjustment", "Adjustment"),
                            ("late_fee", "Late Fee"),
                            ("connection_fee", "Connection Fee"),
                            ("disconnection_fee", "Disconnection Fee"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("bundle", "Multi-Service Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("unit", models.CharField(default="each", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("service_period_start", models.DateTimeField(blank=True, null=True)),
                ("service_period_end", models.DateTimeField(blank=True, null=True)),
                ("is_taxable", models.BooleanField(default=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("section_header", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_billlineitem",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("direct_debit", "Direct Debit"),
                            ("credit_card", "Credit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online", "Online Payment"),
                            ("automatic", "Automatic Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("external_reference", models.CharField(blank=True, max_length=100)),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unallocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("allocation_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[("prepaid", "Prepaid"), ("postpaid", "Postpaid")],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("prepaid", "Prepaid"), ("postpaid", "Postpaid")],
                        max_length=10,
                    ),
                ),
                ("inclusion_rule", models.CharField(blank=True, max_length=100)),
                ("applies_to_next_month", models.BooleanField(default=False)),
                ("billing_handler", models.CharField(max_length=200)),
                ("tariff_handler", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_service_registry",
            },
        ),
    ]
