# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceregistry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_registry_entries",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="billing.bill",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="billing.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billlineitem",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="billing.bill",
            ),
        ),
        migrations.AddField(
            model_name="billlineitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_line_items",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billingrun",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_runs",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billingcycle",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_cycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billingcycle",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_cycles",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billingconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_configs",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billadjustment",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billadjustment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="billing.bill",
            ),
        ),
        migrations.AddField(
            model_name="billadjustment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_adjustments",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceregistry",
            index=models.Index(
                fields=["tenant", "service_code"], name="finance_ser_tenant__3e4f2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceregistry",
            index=models.Index(
                fields=["is_active"], name="finance_ser_is_acti_a30e4f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceregistry",
            unique_together={("tenant", "service_code")},
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["payment", "bill"], name="billing_pay_payment_fcca7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["allocation_date"], name="billing_pay_allocat_6e5d89_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentallocation",
            unique_together={("payment", "bill")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer", "payment_date"],
                name="billing_pay_custome_1764cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="billing_pay_status_b7739e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_reference"], name="billing_pay_payment_55e196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billlineitem",
            index=models.Index(
                fields=["tenant", "bill", "service_type"],
                name="finance_bil_tenant__4ffeca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billlineitem",
            index=models.Index(
                fields=["item_type"], name="finance_bil_item_ty_cea97d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billlineitem",
            index=models.Index(
                fields=["sort_order"], name="finance_bil_sort_or_d23d6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrun",
            index=models.Index(
                fields=["service_type", "run_date"],
                name="billing_bil_service_a37977_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingrun",
            index=models.Index(fields=["status"], name="billing_bil_status_d907f3_idx"),
        ),
        migrations.AddConstraint(
            model_name="billingrun",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "service_type",
                    "period_start",
                    "period_end",
                    "run_date",
                ),
                name="unique_billing_run_per_period",
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["tenant", "customer", "service_type"],
                name="finance_bil_tenant__6a9730_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["next_bill_date"], name="finance_bil_next_bi_1a91fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["is_active"], name="finance_bil_is_acti_d33bfc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billingcycle",
            unique_together={("tenant", "customer", "service_type")},
        ),
        migrations.AddIndex(
            model_name="billingconfig",
            index=models.Index(
                fields=["tenant", "service_code"], name="finance_bil_tenant__88a0df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingconfig",
            index=models.Index(
                fields=["is_active"], name="finance_bil_is_acti_6f3518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billadjustment",
            index=models.Index(
                fields=["bill", "adjustment_type"],
                name="billing_bil_bill_id_72e3da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billadjustment",
            index=models.Index(
                fields=["authorization_date"], name="billing_bil_authori_9457e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["tenant", "customer", "status"],
                name="finance_bil_tenant__bd4796_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["due_date"], name="finance_bil_due_dat_e5eabc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["bill_number"], name="finance_bil_bill_nu_e97e57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["issue_date"], name="finance_bil_issue_d_9ce75d_idx"
            ),
        ),
    ]
