# Generated by Django 4.2.5 on 2025-08-16 01:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Contract ID - references ServiceContract",
                        null=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("broadband", "Broadband"),
                            ("mobile", "Mobile"),
                            ("gas", "Gas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connection_identifier",
                    models.CharField(
                        help_text="Primary identifier (ICP, ONT, Phone Number, SIM IMEI)",
                        max_length=100,
                    ),
                ),
                (
                    "icp_code",
                    models.CharField(
                        blank=True,
                        help_text="Installation Control Point code",
                        max_length=15,
                    ),
                ),
                (
                    "gxp_code",
                    models.CharField(
                        blank=True, help_text="Grid Exit Point code", max_length=10
                    ),
                ),
                ("meter_number", models.CharField(blank=True, max_length=20)),
                (
                    "ont_serial",
                    models.CharField(
                        blank=True, help_text="ONT serial number", max_length=50
                    ),
                ),
                (
                    "line_speed",
                    models.CharField(
                        blank=True, help_text="Line speed capability", max_length=20
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, help_text="Mobile phone number", max_length=20
                    ),
                ),
                (
                    "sim_iccid",
                    models.CharField(
                        blank=True, help_text="SIM card ICCID", max_length=22
                    ),
                ),
                (
                    "device_imei",
                    models.CharField(
                        blank=True, help_text="Device IMEI", max_length=17
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Installation"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("switching", "Switching Provider"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "energy_connection",
            },
        ),
        migrations.CreateModel(
            name="ConnectionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(help_text="Plan identifier", max_length=100),
                ),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        help_text="Plan type (electricity/broadband/mobile)",
                        max_length=50,
                    ),
                ),
                ("assigned_date", models.DateField(default=django.utils.timezone.now)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Plan-specific configuration",
                    ),
                ),
            ],
            options={
                "db_table": "energy_connectionplan",
            },
        ),
    ]
