name: 12. Deploy SpotOn Portal (UAT)

on:
  push:
    branches: [uat]
    paths:
      - 'apps/portal-web/**'
      - '.github/workflows/deploy-portal-uat.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///g')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/portal-web
          file: ./apps/portal-web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/spoton-platform-portal:${{ steps.tag.outputs.image_tag }}
            ghcr.io/${{ github.repository_owner }}/spoton-platform-portal:${{ steps.tag.outputs.branch_name }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deployment Summary
        run: |
          echo "🚀 SpotOn Portal UAT Deployment Complete!"
          echo ""
          echo "📦 Image: ghcr.io/${{ github.repository_owner }}/spoton-platform-portal:${{ steps.tag.outputs.image_tag }}"
          echo "🌿 Branch: ${{ steps.tag.outputs.branch_name }}"
          echo "🔖 Tag: ${{ steps.tag.outputs.image_tag }}"
